/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joseyxz' at '4/11/16 12:45 PM' with Gradle 2.14.1
 *
 * @author joseyxz, @date 4/11/16 12:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
